name: CI/CD - Criação de PR

on:
  push:
    paths:
      - '.github/workflows/github-actions.yml'
      - '.github/workflows/github-actions-cd.yml'

jobs:
  cria-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configura Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Cria nova branch e faz push
        run: |
          git checkout -b ci_cd_formativa_w3
          git add .github/workflows/github-actions.yml .github/workflows/github-actions-cd.yml
          git commit -m "Atualiza arquivos CI/CD"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} ci_cd_formativa_w3

      - name: Instala GitHub CLI
        uses: cli/cli-action@v2

      - name: Cria PR
        run: |
          gh pr create --title "CI/CD Update" \
                       --body "PR automático para CI/CD" \
                       --base main \
                       --head ci_cd_formativa_w3
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
