name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: pylint

  testes:
    runs-on: ubuntu-latest
    needs: build  # ⬅️ Só roda testes depois do build passar
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Definir PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: Executar testes
        run: |
          pytest tests/ --junitxml=pytest-report.xml --html=pytest-report.html

      - name: Publicar Relatórios
        uses: actions/upload-artifact@v4
        with:
          name: pytest-reports
          path: |
            pytest-report.xml
            pytest-report.html