name: Discord
on:
  push:
    branches:
      - '**'  # Escuta todos os pushes para todas as branches

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Discord Webhook
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          embed: |
            {
              "title": "📦 Novo Push Realizado!",
              "description": "**[${{ github.event.head_commit.message }}](${{ github.event.head_commit.url }})**",
              "color": 5814783,
              "fields": [
                {
                  "name": "Autor",
                  "value": "[${{ github.actor }}](https://github.com/${{ github.actor }})",
                  "inline": true
                },
                {
                  "name": "Branch",
                  "value": "`${{ github.ref_name }}`",
                  "inline": true
                },
                {
                  "name": "Ver Commit",
                  "value": "[Clique aqui](${{ github.event.head_commit.url }})"
                }
              ],
              "footer": {
                "text": "Repo: ${{ github.repository }}"
              },
              "timestamp": "${{ github.event.head_commit.timestamp }}"
            }
