name: Continuous Integration - Testing
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - ci_cd_formativa_w3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: pylint

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Simulando deploy após CI
        run: echo "Deploy feito com sucesso após build"