name: Main - Testing
on:
  push:
    branches:
      - main # ou qualquer branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulation CD
        uses: actions/upload-artifact@v4
        with:
          name: project.zip
          path: |
            createdProducts.py
            README.md
            produtos.csv
            config.example.json